modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Vazkii/AkashicTome"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"

[[mods]]
modId="akashictome"
displayName="Akashic Tome"
version="${file.jarVersion}"
authors="Vazkii, MoreThanHidden"
description='''
The book to end all books.
'''
[[dependencies.akashictome]]
    modId="autoreglib"
    mandatory=true
    versionRange="[1.7-52,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.akashictome]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.17,)"
    ordering="AFTER"
    side="BOTH"
