modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Vazkii/AkashicTome"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"

[[mods]]
modId="akashictome"
displayName="Akashic Tome"
version="${file.jarVersion}"
authors="Vazkii, MoreThanHidden, Uraneptus"
description='''The book to end all books.'''

[[dependencies.akashictome]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="AFTER"
    side="BOTH"
