modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Vazkii/AkashicTome"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"

[[mods]]
modId="akashictome"
displayName="Akashic Tome"
version="${version}"
authors="Vazkii, MoreThanHidden"
description='''
The book to end all books.
'''
[[dependencies.akashictome]]
    modId="autoreglib"
    mandatory=true
    versionRange="[1.6-46,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.akashictome]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="AFTER"
    side="BOTH"
